exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
environment:
  GO111MODULE: 'on'
  GOFLAGS: -mod=vendor
plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.25.0
        checksums:
          darwin-amd64: 660a5b0cf5b155e640d3484bc330d49fc5bfd0ab8c26fd62af1e8d64b093fcee
          linux-amd64: ddd80a26dc1d3cd23f32a2ef57bddc5f5e2f1b17a5c2c3b18a997ac5e59281b9
    - locator:
        id: com.palantir.godel-generate-plugin:generate-plugin:1.19.0
        checksums:
          darwin-amd64: 56beca068b502d7085fb6a72942b8dbda94c40f3cca55c3615c38f8034bbce30
          linux-amd64: 5384b3f1b135186c1b805eb66c8f47f96bfdf0736a74d99d233673dfaeafe2d5
