exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
environment:
  GO111MODULE: 'on'
  GOFLAGS: -mod=vendor
plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.33.0
        checksums:
          darwin-amd64: ccc2d3e011108ab5610281b31cd1bdcb04f76c346f957882dc747e90ad4de29d
          linux-amd64: 97e97d474dbf08708bbb6e494699e0fe174cfb31bd6e0526f87804dffd1d97a5
    - locator:
        id: com.palantir.godel-generate-plugin:generate-plugin:1.27.0
        checksums:
          darwin-amd64: 4c62aeab4f285bcaee632ca05712acf4d5045f86ed45b868c15654d199a7e8d6
          linux-amd64: 173a375d427bfb1083501aac8486755d6f536ad6c0bd6225f7fa3935231957f4
